### ISSUE TITLE
Build Warning when Mock a `Sendable` Protocol

### ISSUE THREAD

**Issue by vvisionnn** [Kolos65/Mockable#57]
## Build Warning
> [!WARNING]  
> Stored property 'mocker' of 'Sendable'-conforming class 'MockSomeSendableProtocol' is mutable

## Part of Error Raised Code
```swift
import Foundation
import Mockable

@Mockable
protocol SomeSendableProtocol: Sendable {
    func randomMethod()
    func placeholder()
}
// Expanded Code
#if MOCKING
final class MockSomeSendableProtocol: SomeSendableProtocol, MockableService {
    private var mocker = Mocker<MockSomeSendableProtocol>() // <-- Error Raised Here
    @available(*, deprecated, message: "Use given(_ service:) of Mockable instead. ")
    func given() -> ReturnBuilder {
        .init(mocker: mocker)
    }
......
```

## Minimum Repro Project
[MockedSendable.zip](https://github.com/user-attachments/files/15942712/MockedSendable.zip)

## What Expected
Warning disappeared

**Comment by hainayanda** [comment]
Changing the `mocker` from `var` to `let` and marking the `Mocker` class as `Sendable` will remove this warning.  I don't see any need to make the mocker class mutable unless it simplifies the init requirement, which can be adjusted using convenience init. But this will only move the warning to the `Mocker` class since many of the `Mocker` class members are mutable.

@Kolos65 do you mind if I look into this issue?

**Comment by Kolos65** [comment]
@hainayanda I created a PR, would appreciate your review: #58

**Comment by vvisionnn** [comment]
Thanks @Kolos65 for the quick helping, can you please release a new version for this fix? these warnings are really annoying...
