### ISSUE TITLE
Legacy IssueReporting collides with projects that rely on it.

### ISSUE THREAD

**Issue by briannadoubt** [Kolos65/Mockable#86]
> This change makes it so that newer projects that also leverage `swift-issue-reporting` collide with the following error:
> 
> 
> 
> ```
> 
> multiple similar targets 'IssueReporting', 'IssueReportingTestSupport', 'XCTestDynamicOverlay' appear in package 'swift-issue-reporting' and 'xctest-dynamic-overlay', this may indicate that the two packages are the same and can be de-duplicated by using mirrors. if they are not duplicate consider using the `moduleAliases` parameter in manifest to provide unique names
> 
> ```
> 
> 
> 
> I would think the way to solve this would be to do what `IssueReporting` does and create a `Package@swift-6.swift` file with this reference in it, then fallback to this one if needed. 

 _Originally posted by @briannadoubt in [84c4f7f](https://github.com/Kolos65/Mockable/commit/84c4f7faf1131e806201fd760cb783bb6cd66282#commitcomment-149422244)_

**Comment by briannadoubt** [comment]
Create a PR for this [here](https://github.com/Kolos65/Mockable/pull/87). I don't have the permissions to connect this to the PR

**Comment by briannadoubt** [comment]
I deleted the PR because what I did didn't work

**Comment by Kolos65** [comment]
@briannadoubt I changed this so Mockable is compatible with TCA, im not sure what to do here. Best would be if TCA would update to using issue-reporting also...

**Comment by briannadoubt** [comment]
I think the path I started down would work, with two package files, each consuming a different version of issue reporting based on the Swift language mode.

The issue I ran into is that there are some things that don't compile with Swift 6 language mode, and it would require a refactor. I can maybe try my hand at said refactor! The complexity comes from the swift syntax dependency being shared (with different versions based on the package's language specification) combined with the multiple names for the issue reporting library, so it makes it complicated to support the matrix of all those variables.

I'll spend some time with this!

As an aside, this package is wonderfully designed and this tool is an amazing contribution to the community! I've seen it used in all kinds of tools around me, and it makes consuming the swift-dependencies protocol pattern so nice and clean. So the effort on this would be worthwhile to modernize to Swift 6 language mode 😇 Thank you 😊

**Comment by Kolos65** [comment]
@briannadoubt there is already a branch where I implemented swift 6 support, see #64 I just hadn't had the time to finish it yet.

**Comment by Kolos65** [comment]
@briannadoubt I merged Swift 6 support changes and would like to revisit this issue. Can you help me understand your use-case better?

For more context, I created #84 so that Mockable is compatible with pointfree libs.

Pointfree packages use the old name of swift-issue-reporting in their package manifest:

* [TCA / Package@swift-6.0.swift](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Package%40swift-6.0.swift)
* [TCA / Package.swift](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Package.swift)
* [swift-dependencies / Package@swift-6.0.swift](https://github.com/pointfreeco/swift-dependencies/tree/main)
* etc...

all have
```swift
.package(url: "https://github.com/pointfreeco/xctest-dynamic-overlay", from: "1.3.0")
```
in the manifest.

This means, that if Mockable uses the new `swift-issue-reporting` instead of the old package name, you will get the duplication error you posted above if you try to depend on Mockable and TCA together.

If you project uses issue reporting as a dependency I suggest following this to resolve the duplication issue.

**Comment by briannadoubt** [comment]
I think the discrepancy comes when the package has `swiftLanguageModes: [.v6]` on it. Then the `swift-issue-reporting` is used instead of `xctest-dynamic-overlay`

**Comment by Kolos65** [comment]
Can you help me repro that? As I wrote above, I don't see how you run into this issue:
* Do you yourself use `swift-issue-reporting` in your own project?
    * pls change it to use `xctest-dynamic-overlay ` bacuse I want to keep compatibility with pointfree libs (delete derived data + swiftpm cache after)
* Do you use an other lib that depends on `swift-issue-reporting`?
    * which one?

**Comment by Kolos65** [comment]
Im closing this for the reasons described above, reopen if needed.
